---
- name: Install required Debian packages
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - wget
    - curl
    - make
    - mongodb
    - git
    - build-essential
    - apt-transport-https

- name: Add nodesource apt key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
           state=present

- name: Add nodesource apt repository
  apt_repository: repo="deb https://deb.nodesource.com/node_0.12 {{ansible_distribution_release}} main"
                  update_cache=yes
                  state=present

- name: Install nodejs from nodesource
  apt: name=nodejs
       state=present
       update_cache=yes
       cache_valid_time=86400
