# Create openhim user
- name: Create user to run openhim
  user: name={{openhim_user}}
        state=present

- name: Create {{openhim_dir}}
  file: path={{openhim_dir}}
        state=directory

- name: Install openhim from git
  git: dest={{openhim_dir}}
       repo=https://github.com/jembi/openhim-core-js.git
       version={{openhim_git_branch}}
  when: openhim_git_branch is defined

- name: Install dependencies with npm
  npm: path={{openhim_dir}}
       executable={{nodejs_path}}/bin/npm

- name: Install grunt with npm (local)
  npm: name=grunt
       state=present
       path={{openhim_dir}}
       executable={{nodejs_path}}/bin/npm

- name: Install grunt with npm (global)
  npm: name=grunt-cli
       state=present
       global=yes
       executable={{nodejs_path}}/bin/npm

# Note: This will require node to be in the $PATH
- name: Build openhim with grunt
  shell: "{{nodejs_path}}/bin/grunt build chdir={{openhim_dir}}"
