---
# Cleanup if (re)deploying
- include: cleanup.yml
  when: openhim_deploy_local

- include: Debian.yml
  when: ansible_os_family == "Debian"

# Install OpenHIM Core
- include: deploy.yml
  when: openhim_deploy_local

## Install openhim-core via npm if not installing from source or deploy
- name: Install openhim-core from npm
  npm: name=openhim-core
       global=yes
       state=present
  when: not openhim_deploy_local

# Install Openhim-xds-mediator
- include: xds-mediator.yml
  when: openhim_xds_mediator_install

- name: Enable OpenHIM Core services
  service: name={{item}} state=started enabled=yes
  with_items:
    - openhim-core
#    - openhim-xds-mediator
  when: ansible_os_family == "Debian"

