---
- include: Debian.yml
  when: ansible_os_family == "Debian"

- name: Install openhim-core from npm
  npm: name=openhim-core
       global=yes
       state=present

- name: Install openhim-core config
  template: src=default.json.j2
            dest=/usr/lib/node_modules/openhim-core/config/default.json

- name: Install openhim-core upstart job
  template: src=openhim-core.conf.j2
            dest=/etc/init/openhim-core.conf
            mode=0644
            owner=root
            group=root
  when: ansible_distribution == "Ubuntu"

- name: Enable OpenHIM Core services
  service: name={{item}} state=started enabled=yes
  with_items:
    - openhim-core
  when: ansible_distribution == "Ubuntu"

# Install Openhim-xds-mediator
- include: xds-mediator.yml
  when: openhim_xds_mediator_install
