---
# Install node.js. Thanks https://github.com/AnsibleShipyard/ansible-nodejs.
- name: Checking installed version of nodejs
  shell: /usr/bin/test "$({{nodejs_path}}bin/node -v 2> /dev/null)" = {{nodejs_version_tag}}
  register: wanted_version_installed
  ignore_errors: True
  changed_when: "wanted_version_installed.rc == 1"

- name: Download nodejs {{nodejs_version_tag}}
  get_url: url={{nodejs_tarball_url}} dest=/tmp/{{nodejs_file_name}}
  when: wanted_version_installed.rc == 1

- name: Verify SHASUM of nodejs {{nodejs_version_tag}}
  shell: curl {{nodejs_shasum_url}} | grep {{nodejs_file_name}} | sha1sum -c chdir=/tmp/
  when: wanted_version_installed.rc == 1

- name: Unpack nodejs {{nodejs_version_tag}}
  unarchive: src=/tmp/{{nodejs_file_name}}
             dest=/tmp
             copy=no
  when: wanted_version_installed.rc == 1

- name: Install nodejs to {{nodejs_path}}
  shell: "cp -r /tmp/{{nodejs_file_tag}}*/* /usr/local/"
