






- name: Ensure openhim directories have correct permissions
  file: path={{item}}
        group={{openhim_user}}
        owner={{openhim_user}}
        recurse=yes
        state=directory
  with_items:
   - "{{openhim_dir}}"
