---
- name:  Install required packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - openjdk-7-jre
    - mysql-server
    - python-mysqldb
    - unzip

- name: Fetch openhim release
  get_url: url=https://github.com/jembi/openhim/releases/download/v{{ openhim_version }}/openhim-{{ openhim_version }}.zip dest=/opt/openhim-{{ openhim_version }}.zip

- name: Extract openhim to /opt/openhim
  command: creates=/opt/openhim unzip /opt/openhim-{{ openhim_version }}.zip -d /opt/openhim

- name: Set mysql root password
  mysql_user: check_implicit_admin=yes login_user=root login_password={{ mysql_root_password }} name=root password={{ mysql_root_password }} state=present

- name: create db
  mysql_db: db=interoperability_layer login_user=root login_password={{ mysql_root_password }} state=present

- name: Modify file for import
  lineinfile: dest=/opt/openhim/classes/create_database.sql regexp="create database*" state=absent

- name: Import test db
  mysql_db: db=interoperability_layer login_user=root login_password={{ mysql_root_password }} state=import target=/opt/openhim/classes/create_database.sql

- name: Apply database updates
  mysql_db: name=interoperability_layer login_user=root login_password={{ mysql_root_password }} target={{ item }} state=import
  with_items:
   - /opt/openhim/classes/update_database_1.sql
   - /opt/openhim/classes/update_database_2.sql

- name: create mysql himuser
  mysql_user: name=himuser password={{ himuser_password }} login_user=root login_password={{ mysql_root_password }} state=present priv=interoperability_layer.*:ALL

- name: backup /etc/hosts
  command: cp /etc/hosts /etc/hosts.openhim.bak

- name: Insert temporary /etc/hosts
  copy: src=hosts-ldap dest=/etc/hosts

- name: Install openldap
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - slapd
    - ldap-utils

- name: Restore /etc/hosts
  command: mv /etc/hosts.openhim.bak /etc/hosts

- name: Delete the configuration directory
  file: path=/etc/ldap/slapd.d state=absent

- name: Create new ldap directory
  file: dest=/var/lib/ldap/{{ domain_name }} state=directory owner=openldap group=openldap

- name: Generate the root password for ldap
  shell: slappasswd -s {{ ldap_pass }} 
  register: root_password

- name: Copy slapd.conf
  template: src=slapd.conf.j2 dest=/etc/ldap/slapd.conf owner=openldap group=openldap

- name: Restart slapd
  service: name=slapd state=restarted

- name: Fetch Mule
  get_url: url=http://dist.codehaus.org/mule/distributions/mule-standalone-3.4.0.tar.gz dest=/tmp

- name: Extract Mule
  command: chdir=/opt tar xzf /tmp/mule-standalone-3.4.0.tar.gz -C /opt  

- name: Insert openhim config HIM-core
  template: src=HIM-core.properties.j2 dest=/opt/mule-standalone-3.4.0/conf/HIM-core.properties

- name: Insert openhim config defaultchannel-mapping
  template: src=defaultchannel-mapping.json.j2 dest=/opt/mule-standalone-3.4.0/conf/defaultchannel-mapping.json

- name: Insert openhim config patientMediator
  template: src=patientMediator.properties.j2 dest=/opt/mule-standalone-3.4.0/conf/patientMediator.properties

- name: Insert openhim config encounter-mediator
  template: src=encounter-mediator.properties.j2 dest=/opt/mule-standalone-3.4.0/conf/encounter-mediator.properties
  
- name: Insert openhim init script
  template: src=openhim.j2 dest=/etc/init.d/openhim mode=0755 owner=root group=root

- name: Deploy openhim
  command: cp /opt/openhim-{{ openhim_version }}.zip /opt/mule-standalone-3.4.0/apps/

- name: Deploy openhim-encounter
  get_url: url=https://github.com/jembi/openhim-encounter-orchestrator/releases/download/v{{ encounter_version }}/openhim-encounter-mediator-{{ encounter_version }}.zip dest=/opt/mule-standalone-3.4.0/apps/openhim-encounter-mediator-{{ encounter_version }}.zip

- name: Deploy openhim-patient
  get_url: url=https://github.com/jembi/openhim-openempi-patient-adapter/releases/download/v{{ patient_version }}/openhim-openempi-patient-adapter-{{ patient_version }}.zip dest=/opt/mule-standalone-3.4.0/apps/openhim-openempi-patient-adapter-{{ patient_version }}.zip

- name: Start and enable openhim at boot
  service: name=openhim state=started enabled=yes
