---
- name: create webui user
  user: name=webui state=present shell=/bin/bash

- name: lock webui user account
  command: passwd -l webui

- name: Install required pacakges for openhim-webui
  apt: update_cache=yes name={{ item }} state=installed
  with_items:
   - libmysqlclient-dev
   - python-dev
   - python-pip
   - git

- name: Install packges with pip
  pip: name={{ item }} state=present 
  with_items:
   - cherrypy
   - mysql-python
   - mako
   - ndg-httpsclient

- name: clone openhim-webui repo
  git: repo=https://github.com/jembi/openhim-webui.git dest=/opt/openhim-webui

- name: Apply database updates
  mysql_db: name=interoperability_layer login_user=root login_password={{ mysql_root_password }} target={{ item }} state=import
  with_items:
   - /opt/openhim-webui/resources/update_database_1.sql
   - /opt/openhim-webui/resources/update_database_2.sql
   - /opt/openhim-webui/resources/update_database_3.sql
   - /opt/openhim-webui/resources/update_database_4.sql
   - /opt/openhim-webui/resources/update_database_5.sql

- name: insert database.cfg
  template: src=database.cfg.j2 dest=/opt/openhim-webui/resources/database.cfg owner=webui group=webui
  notify: restart openhim-webui

- name: insert server.cfg
  template: src=server.cfg.j2 dest=/opt/openhim-webui/resources/server.cfg owner=webui group=webui
  notify: restart openhim-webui

- name: insert auth.cfg
  template: src=auth.cfg.j2 dest=/opt/openhim-webui/resources/auth.cfg owner=webui group=webui
  notify: restart openhim-webui

- name: insert openhim-webui init script
  template: src=openhim-webui.j2 dest=/etc/init.d/openhim-webui mode=0755
  notify: restart openhim

- name: start openhim-webui and enable at boot
  service: name=openhim-webui state=started enabled=yes
