---
- name: Generate the root password for ldap
  shell: slappasswd -s {{ ldap_pass }}
  register: root_password

- name: Copy ldif to import
  template: src=ldap-auth-pre-prod.ldif dest=/opt/openhim/classes/ldap-auth-pre-prod.ldif 

- name: Import ldif 
  command: ldapadd -c -x -D {{ openldap_root_dn }} -w {{ ldap_pass }} -f /opt/openhim/classes/ldap-auth-pre-prod.ldif
  notify:
   -  restart slapd
